name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: config github-token
      run: composer config -g github-oauth.github.com ${{ secrets.OAUTH_TOKEN }}

    - name: build the packages
      run: php ./bin/satis build ./satis.json ./public

    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        target_branch: gh-pages
        build_dir: ./public
      env:
        GITHUB_TOKEN: ${{ secrets.OAUTH_TOKEN }}